version: 2

requirements:
  signed_off_by:
    required: true

always_pending:
  title_regex: 'WIP'
  explanation: 'Work in progress...'

group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^(Approved|LGTM|:shipit:|:\+1:|Engage)'
    reject_regex: '^(Rejected|:-1:|Borg)'
  reset_on_push:
    enabled: true

groups:
  example-reviewers:
    required: 1

    users:
      - mueller-ma-bot

    conditions:
      branches:
        - master  # this group only reviews when PR is merging into master
      files:
        include:
          - '*.md'
        exclude:
          - 'README.md'
      labels:
        - bug

    approve_by_comment:
      enabled: true
      approve_regex: '^LGTM'  # overrides the default '^:\+1:'

    author_approval:
      required: true

    reset_on_reopened:
      enabled: true

    reject_value: -3
