language: android
jdk: oraclejdk8

env:
  global:
   - ANDROID_TARGET=android-26
   - ANDROID_ABI=x86
   - TAG=google_apis
   - function emulator { cd "$(dirname "$(which emulator)")" && ./emulator "$@"; }
   - $emulator="/usr/local/android-sdk/tools/emulator"
  
before_cache:
  - cd ${TRAVIS_BUILD_DIR}/gradle/caches/
  - find . -name "*.lock" -exec rm -rfv {} \;
  - cd ${TRAVIS_BUILD_DIR}

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

notifications:
  email: false

android:
  components: # Cookbooks version: https://github.com/travis-ci/travis-cookbooks/tree/9c6cd11
    - tools # Update preinstalled tools from revision 24.0.2 to 24.4.1
    - build-tools-25.0.2 # Match build-tools version used in build.gradle
    - platform-tools # Update platform-tools to revision 25.0.3+
    - tools # Update tools from revision 24.4.1 to 25.2.5
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
    - android-${ANDROID_TARGET}

install:
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  - echo "y" | android update sdk -a --no-ui --filter ${ANDROID_TARGET}
  - echo "y" | android update sdk -a --no-ui --filter sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
  - echo yes | sdkmanager "system-images;${ANDROID_TARGET};google_apis_playstore;${ANDROID_ABI}"
  # Show version and download Gradle Wrapper if it's not already cached
  - ./gradlew --version
  # Check components status
  - sdkmanager --list || true

script:
  - android list target
  - ./gradlew clean build
  - ./gradlew test
  - ./gradlew jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test --abi $ANDROID_ABI -k "system-images;android-26;google_apis_playstore;x86"
  - type -a emulator
  - $emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
  
after_script:
  # Show lint results
  - cat ${TRAVIS_BUILD_DIR}/*/build/reports/lint-results.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
