language: android
jdk: oraclejdk8
env:
  global:
  - secure: fMBUkSsCBTw/U907w7Xm/yNzw4lq9yt7zFy0JyEZrA543LI7zQRIclIOtsDTUs0bwY+4KI08MNoYPLJ4TQhSJaH4wQ8b9C5TRsqXNfc0V718TcuYqSXqU6VPRVtX46/fCEWv/HAs0ksUKrHIlpWOwLPQpYDcKxwwlUndaakYKJ8=

before_cache:
- find $HOME/.gradle/caches/ -name "*.lock" -exec rm -rfv {} \;
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
  
notifications:
  email: false

android:
  components:
  - tools
  - build-tools-25.0.2
  - platform-tools
  - tools
  - android-22
  - sys-img-armeabi-v7a-android-22

stages:
    - test
    - deploy

jobs:
    include:
        - stage: test
          script: bash travis/install.sh && ./gradlew fossTest
        - script: bash travis/install.sh && ./gradlew fullTest
        - script: bash travis/install.sh && bash travis/start-emulator.sh && ./gradlew fossConnectedCheck
        - script: bash travis/install.sh && bash travis/start-emulator.sh && ./gradlew fullConnectedCheck
        - script: bash travis/install.sh && ./gradlew jacocoTestReport && bash <(curl -s https://codecov.io/bash)
        - script: bash assets/store_descriptions/generate_and_validate.sh
        - stage: deploy
          script: bash travis/prepare-deploy.sh
