language: android
jdk: oraclejdk8
env:
  global:
  - secure: fMBUkSsCBTw/U907w7Xm/yNzw4lq9yt7zFy0JyEZrA543LI7zQRIclIOtsDTUs0bwY+4KI08MNoYPLJ4TQhSJaH4wQ8b9C5TRsqXNfc0V718TcuYqSXqU6VPRVtX46/fCEWv/HAs0ksUKrHIlpWOwLPQpYDcKxwwlUndaakYKJ8=

before_cache:
- find $HOME/.gradle/caches/ -name "*.lock" -exec rm -rfv {} \;
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
  
notifications:
  email: false

android:
  components:
  - tools
  - build-tools-25.0.2
  - platform-tools
  - tools
  - android-22
  - sys-img-armeabi-v7a-android-22

stages:
    - compile
    - unitTest
    - androidTest
    - deploy

jobs:
    include:
        - stage: compile
          script: bash travis/install.sh
        - stage: unitTest
          script: ./gradlew FossTest
          script: ./gradlew FullTest
