language: android
jdk: oraclejdk8
env:
  global:
  - secure: fMBUkSsCBTw/U907w7Xm/yNzw4lq9yt7zFy0JyEZrA543LI7zQRIclIOtsDTUs0bwY+4KI08MNoYPLJ4TQhSJaH4wQ8b9C5TRsqXNfc0V718TcuYqSXqU6VPRVtX46/fCEWv/HAs0ksUKrHIlpWOwLPQpYDcKxwwlUndaakYKJ8=
  - ANDROID_HOME="/home/travis/build/mueller-ma-bot/sdk"
  - PATH="$PATH:${ANDROID_HOME}/tools"
  - DEBIAN_FRONTEND=noninteractive
  - VERSION_SDK_TOOLS="3859397"
before_cache:
- cd ${TRAVIS_BUILD_DIR}/gradle/caches/
- find . -name "*.lock" -exec rm -rfv {} \;
- cd ${TRAVIS_BUILD_DIR}
cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
notifications:
  email: false
android:
  components:
  - tools
  - build-tools-25.0.2
  - platform-tools
  - tools
install:
- curl -s https://dl.google.com/android/repository/sdk-tools-linux-${VERSION_SDK_TOOLS}.zip > /home/travis/build/mueller-ma-bot/sdk.zip && unzip /home/travis/build/mueller-ma-bot/sdk.zip -d /home/travis/build/mueller-ma-bot/sdk && rm -v /home/travis/build/mueller-ma-bot/sdk.zip
- mkdir -p $ANDROID_HOME/licenses/ && echo "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/android-sdk-license && echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
- mkdir -p ~/.android
- touch ~/.android/repositories.cfg
- echo yes | ${ANDROID_HOME}/tools/bin/sdkmanager --update
- echo yes | ${ANDROID_HOME}/tools/bin/sdkmanager "add-ons;addon-google_apis-google-24" "build-tools;26.0.2" "extras;android;m2repository" "extras;google;m2repository" "extras;google;google_play_services" "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2" "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2" "platform-tools" "platforms;android-26" > /dev/null
#- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
#- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
- ./gradlew --version
- sdkmanager --list || true
script:
- ./gradlew clean assemble
- ./gradlew test
- echo "--" > .adjust_token
# - ./gradlew jacocoTestReport
after_script:
- cat ${TRAVIS_BUILD_DIR}/*/build/reports/lint-results.xml
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- openssl aes-256-cbc -K $encrypted_903a93ed2309_key -iv $encrypted_903a93ed2309_iv
  -in keystore.enc -out keystore -d
- cp $TRAVIS_BUILD_DIR/keystore $HOME
- cd mobile/build/outputs/apk/full/release
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore
  -storepass $storepass mobile-full-release-unsigned.apk sign
- jarsigner -verify mobile-full-release-unsigned.apk
- ${ANDROID_HOME}/build-tools/25.0.2/zipalign -v 4 mobile-full-release-unsigned.apk mobile-full-release.apk
deploy:
  provider: releases
  prerelease: true
  file: mobile-full-release.apk
  skip_cleanup: true
  overwrite: true
  on:
    repo: openhab/openhab.android
    jdk: oraclejdk8
    branch: master
    tags: true
  api_key:
    secure: JaDHY9PaBF625dfulN8ygmOvBk3ZDmnZZDr7IPwqJ9hZ+4WzS85om8F9+bgQlZTDDVUeaNZ03ZkfRZ81g9D0EEHF5WSFqgN8aUcNoAa8ViBFAQUeO1uTjVkiP0G7JOVRyW59HTTk6Cjr5eiGKkmeIGT9KgUUi+4Bw/6Quag8f8Y=
